
#One more easter egg from python which returns SyntaxError: not a chance. It means that delimiting blocks by braces instead of indentation will never be implemented.
from __future__ import braces

# Well know easter egg from pyhton which will represent The Zen of Python
import this

# Opens up a web browser that points to the classic XKCD comic mentioning Python.
import antigravity

#__hello__ is a frozen module intended as a test case for frozen module support. It's source code is automatically generated by the Python freeze utility.
import __hello__
